export const fakeCardNews = [
  {
    newsId: 1,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر الأول",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 10,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 2,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 3,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 4,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 5,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 6,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 7,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 8,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 9,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 10,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
];
