export const fakeCardNews = [
  {
    newsId: 1,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر الأول",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 10,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 2,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 3,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 4,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 5,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 6,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 7,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 8,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 9,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
  {
    newsId: 10,
    newsCategoryId: 1,
    cardImageLink: "https://picsum.photos/200/300",
    title: "الخبر hgehkd",
    description:
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.... ",
    newsDate: "2024-01-01",
    newsTime: "12:00:00",
    newsBodyText: "هذا الوصف مخصص للخبر الاول",
    newsLink: "string",
    views: 15,
    newsCategoryName: "الصنف الاول",
  },
];

export const AcademicProgramFakeData = [
  {
    id: 1,
    order: 1,
    category: "برامج الدبلوم",
    name: " المعهد التخصصي لتكوين الأئمة والخطباء",
    image: "https://picsum.photos/200/300",
    status: true,
  },
  {
    id: 2,
    order: 2,
    category: "برامج الدبلوم",
    name: "المعهد التخصصي لتكوين الأئمة والخطباء",
    image: "https://picsum.photos/200/300",
    status: false,
  },
  {
    id: 3,
    order: 3,
    category: "برامج الدبلوم",
    name: "المعهد التخصصي لتكوين الأئمة والخطباء",
    image: "https://picsum.photos/200/300",
    status: false,
  },
  {
    id: 4,
    order: 4,
    category: "برامج الدبلوم",
    name: "المعهد التخصصي لتكوين الأئمة والخطباء",
    image: "https://picsum.photos/200/300",
    status: false,
  },
  {
    id: 5,
    order: 5,
    category: "برامج الدبلوم",
    name: "المعهد التخصصي لتكوين الأئمة والخطباء",
    image: "https://picsum.photos/200/300",
    status: false,
  },
  {
    id: 6,
    order: 6,
    category: "برامج الدبلوم",
    name: "المعهد التخصصي لتكوين الأئمة والخطباء",
    image: "https://picsum.photos/200/300",
    status: false,
  },
];

export const FaqsFakeData = [
  {
    id: 1,
    order: 1,
    question: "برامج الدبلوم",
    answer: " المعهد التخصصي لتكوين الأئمة والخطباء",
    status: true,
  },
  {
    id: 2,
    order: 2,
    question: "برامج الدبلوم",
    answer: " المعهد التخصصي لتكوين الأئمة والخطباء",
    status: false,
  },
  {
    id: 3,
    order: 3,
    question: "برامج الدبلوم",
    answer: " المعهد التخصصي لتكوين الأئمة والخطباء",
    status: false,
  },
  {
    id: 4,
    order: 4,
    question: "برامج الدبلوم",
    answer: " المعهد التخصصي لتكوين الأئمة والخطباء",
    status: false,
  },
  {
    id: 5,
    order: 5,
    question: "برامج الدبلوم",
    answer: " المعهد التخصصي لتكوين الأئمة والخطباء",
    status: false,
  },
  {
    id: 6,
    order: 6,
    question: "برامج الدبلوم",
    answer: " المعهد التخصصي لتكوين الأئمة والخطباء",
    status: false,
  },
];
